### ISSUE TITLE
An error with your code

### ISSUE THREAD

**Issue by burness** [JonathanRaiman/infogan#4]
@JonathanRaiman , Thanks for your code here! When I run it with tensorflow 0.12.1. It seems to met a error 

```
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    train()
  File "/Users/burness/git_repository/dl_opensource/toy_projects/gan/tensorflow-infogan/infogan/__init__.py", line 287, in train
    use_batch_norm=use_batch_norm
  File "/Users/burness/git_repository/dl_opensource/toy_projects/gan/tensorflow-infogan/infogan/__init__.py", line 60, in discriminator_f
orward
    debug=debug)
  File "/Users/burness/git_repository/dl_opensource/toy_projects/gan/tensorflow-infogan/infogan/tf_utils.py", line 109, in run_network
    reuse=False
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with
_args
    return func(*args, **current_args)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 849, in convolution
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/Users/burness/git_repository/dl_opensource/toy_projects/gan/tensorflow-infogan/infogan/tf_utils.py", line 41, in conv_batch_norm
    ema_apply_op = ema.apply([mean, variance])
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_ave
rage
    update_delta = _zero_debias(variable, value, decay)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable discriminator/layer_0/batch_norm/discriminator_1/layer_0/batch_norm/discriminator_1/layer_0/batch_norm/moments/norma
lize/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in Va
rScope?
```
I seems that the reuse cause the error, could you help me with it

**Comment by JonathanRaiman** [comment]
@burness Thank you for sharing the issue. I'll try to reproduce this to understand what was happening (I was running an earlier tensorflow when I last ran this).
